plugin:
    name: 'offline.gdpr::lang.plugin.name'
    description: 'offline.gdpr::lang.plugin.description'
    author: OFFLINE
    icon: icon-gavel
    homepage: 'https://github.com/OFFLINE-GmbH/oc-gdpr-plugin'
permissions:
    offline.gdpr.manage_cookie_consent:
        tab: 'offline.gdpr::lang.plugin.name'
        label: 'offline.gdpr::lang.permissions.manage_cookie_consent'
    offline.gdpr.manage_data_retention:
        tab: 'offline.gdpr::lang.plugin.name'
        label: 'offline.gdpr::lang.permissions.manage_data_retention'
    offline.gdpr.manage_cookie_groups:
        tab: 'offline.gdpr::lang.plugin.name'
        label: 'offline.gdpr::lang.permissions.manage_cookie_groups'
    offline.gdpr.manage_cookie_info:
        tab: 'offline.gdpr::lang.plugin.name'
        label: 'offline.gdpr::lang.permissions.manage_cookie_info'